[project]
name = "week9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keras>=3.12.0",
    "numpy>=2.3.5",
    "tensorflow>=2.20.0",
    "torchvision>=0.24.1",
]
